/* ============================================================
   Beauty Lodge by Anna — site behavior
   ============================================================ */

const SETMORE_URL = "https://beautylodgebyanna.setmore.com";
const INSTAGRAM_URL =
  "https://www.instagram.com/beauty_lodge_by_anna/";

/*
  Upcoming events are generated by GitHub Actions from Anna's
  public Google Calendar and saved locally as assets/events.json.
*/
const EVENTS_JSON_URL = "assets/events.json";
const MAX_POPUP_EVENTS = 6;
const CALENDAR_REFRESH_MINUTES = 15;

function escapeEventText(value = "") {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function parseEventDate(value) {
  if (!value) return null;
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? null : date;
}

function formatEventMonth(date) {
  return new Intl.DateTimeFormat("en-US", {
    month: "short"
  }).format(date).toUpperCase();
}

function formatEventDay(date) {
  return new Intl.DateTimeFormat("en-US", {
    day: "numeric"
  }).format(date);
}

function formatEventSchedule(event) {
  const start = parseEventDate(event.start);
  const end = parseEventDate(event.end);

  if (!start) return "Date to be announced";

  const dateText = new Intl.DateTimeFormat("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
    year: "numeric"
  }).format(start);

  if (event.allDay) return dateText;

  const startTime = new Intl.DateTimeFormat("en-US", {
    hour: "numeric",
    minute: "2-digit"
  }).format(start);

  if (!end) return `${dateText} · ${startTime}`;

  const endTime = new Intl.DateTimeFormat("en-US", {
    hour: "numeric",
    minute: "2-digit"
  }).format(end);

  return `${dateText} · ${startTime}-${endTime}`;
}

function getShortDescription(description = "") {
  const cleaned = String(description)
    .replace(/<[^>]*>/g, "")
    .replace(/\s+/g, " ")
    .trim();

  if (!cleaned) return "";
  return cleaned.length <= 180
    ? cleaned
    : `${cleaned.slice(0, 180).trim()}...`;
}

function createPopupEventCard(event) {
  const start = parseEventDate(event.start);
  if (!start) return "";

  const title = escapeEventText(
    event.title || "Beauty Lodge Pop-Up"
  );
  const location = escapeEventText(event.location || "");
  const description = escapeEventText(
    getShortDescription(event.description || "")
  );
  const schedule = escapeEventText(
    formatEventSchedule(event)
  );

  const locationHtml = location
    ? `
      <p class="popup-location">
        <svg
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="1.6"
          aria-hidden="true"
        >
          <path d="M12 21s6-5.2 6-11a6 6 0 1 0-12 0c0 5.8 6 11 6 11Z" />
          <circle cx="12" cy="10" r="2.2" />
        </svg>
        <span>${location}</span>
      </p>
    `
    : "";

  const descriptionHtml = description
    ? `<p class="popup-description">${description}</p>`
    : "";

  return `
    <article class="popup-card">
      <div class="popup-date">
        <span class="popup-month">${formatEventMonth(start)}</span>
        <span class="popup-day">${formatEventDay(start)}</span>
      </div>

      <div class="popup-content">
        <h4>${title}</h4>
        <p class="popup-schedule">${schedule}</p>
        ${locationHtml}
        ${descriptionHtml}
      </div>
    </article>
  `;
}

function configureDynamicInstagramLink(container) {
  const button = container.querySelector("[data-ig]");

  if (button) {
    button.href = INSTAGRAM_URL;
    button.target = "_blank";
    button.rel = "noopener";
  }
}

function renderEmptyCalendar(container) {
  container.innerHTML = `
    <div class="popup-empty">
      <p class="eyebrow">More Dates Coming Soon</p>
      <h4>No upcoming pop-ups are scheduled yet.</h4>
      <p>
        Follow Beauty Lodge on Instagram for announcements and
        newly added market dates.
      </p>
      <a class="btn btn-light btn-sm" data-ig href="#">
        Follow on Instagram
      </a>
    </div>
  `;

  configureDynamicInstagramLink(container);
}

function renderCalendarError(container) {
  container.innerHTML = `
    <div class="popup-empty">
      <p class="eyebrow">Upcoming Events</p>
      <h4>The event calendar is temporarily unavailable.</h4>
      <p>
        Please check back soon or visit Instagram for the latest
        pop-up and market announcements.
      </p>
      <a class="btn btn-light btn-sm" data-ig href="#">
        Follow on Instagram
      </a>
    </div>
  `;

  configureDynamicInstagramLink(container);
}

async function loadPopupEvents() {
  const container = document.getElementById("popup-events");
  if (!container) return;

  try {
    const cacheBuster = Date.now();
    const response = await fetch(
      `${EVENTS_JSON_URL}?v=${cacheBuster}`,
      { cache: "no-store" }
    );

    if (!response.ok) {
      throw new Error(`Events request returned ${response.status}`);
    }

    const data = await response.json();
    const now = new Date();

    const events = Array.isArray(data.events)
      ? data.events
          .filter((event) => {
            const end =
              parseEventDate(event.end) ||
              parseEventDate(event.start);
            return end && end >= now;
          })
          .sort(
            (a, b) =>
              parseEventDate(a.start) -
              parseEventDate(b.start)
          )
          .slice(0, MAX_POPUP_EVENTS)
      : [];

    if (events.length === 0) {
      renderEmptyCalendar(container);
      return;
    }

    container.innerHTML = events
      .map(createPopupEventCard)
      .join("");
  } catch (error) {
    console.error("Unable to load upcoming events:", error);
    renderCalendarError(container);
  }
}

document.addEventListener("DOMContentLoaded", () => {
  document.querySelectorAll("[data-book]").forEach((el) => {
    el.classList.add("anywhere-book-now-button");
    el.setAttribute("data-booking-url", SETMORE_URL);
    el.setAttribute("data-new-tab", "false");
    el.setAttribute("href", SETMORE_URL);
    el.setAttribute("rel", "noopener");
  });

  if (!document.getElementById("anywhere_book_now_script")) {
    const script = document.createElement("script");
    script.id = "anywhere_book_now_script";
    script.src =
      "https://assets.setmore.com/integration/book-now/live/v1/anywhere-book-now.js";
    document.body.appendChild(script);
  }

  document.querySelectorAll("[data-ig]").forEach((el) => {
    el.setAttribute("href", INSTAGRAM_URL);
    el.setAttribute("target", "_blank");
    el.setAttribute("rel", "noopener");
  });

  const toggle = document.querySelector(".nav-toggle");
  const links = document.querySelector(".nav-links");

  if (toggle && links) {
    toggle.addEventListener("click", () => {
      const open = links.classList.toggle("open");
      toggle.setAttribute(
        "aria-expanded",
        open ? "true" : "false"
      );
    });

    links.querySelectorAll("a").forEach((anchor) => {
      anchor.addEventListener("click", () => {
        links.classList.remove("open");
        toggle.setAttribute("aria-expanded", "false");
      });
    });
  }

  const reduceMotion = window.matchMedia(
    "(prefers-reduced-motion: reduce)"
  ).matches;
  const revealItems = document.querySelectorAll(".reveal");

  if (
    reduceMotion ||
    !("IntersectionObserver" in window)
  ) {
    revealItems.forEach((el) => el.classList.add("in"));
  } else {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add("in");
            observer.unobserve(entry.target);
          }
        });
      },
      {
        threshold: 0.12,
        rootMargin: "0px 0px -60px 0px"
      }
    );

    revealItems.forEach((el) => observer.observe(el));
  }

  loadPopupEvents();

  window.setInterval(
    loadPopupEvents,
    CALENDAR_REFRESH_MINUTES * 60 * 1000
  );
});
