/* ============================================================
   Beauty Lodge by Anna — site behavior
   ============================================================ */

const SETMORE_URL = "https://beautylodgebyanna.setmore.com";
const INSTAGRAM_URL =
  "https://www.instagram.com/beauty_lodge_by_anna/";

/*
  Upcoming events are generated by GitHub Actions from Anna's
  public Google Calendar and saved locally as assets/events.json.
*/
const EVENTS_JSON_URL = "assets/events.json";
const MAX_POPUP_EVENTS = 6;
const CALENDAR_REFRESH_MINUTES = 15;

function getPageName() {
  const path = window.location.pathname.split("/").pop() || "index.html";

  if (path === "index.html") return "home";

  return path.replace(/\.html$/i, "") || "home";
}

function getButtonLocation(element) {
  const locationSelectors = [
    [".nav", "navigation"],
    [".hero", "hero"],
    [".svc-card", "service_card"],
    [".lash-finder", "lash_finder"],
    [".jewelry-finder", "jewelry_style_finder"],
    [".event-inquiry-section", "jewelry_event_inquiry"],
    [".teaser", "jewelry_teaser"],
    [".jcta", "jewelry_cta"],
    [".events", "events"],
    [".team-cta", "team_cta"],
    [".team-member", "team_profile"],
    [".location-section", "location"],
    [".contact-page", "contact_page"],
    [".footer", "footer"],
    [".walnex-promo", "walnex_promo"]
  ];

  const match = locationSelectors.find(([selector]) =>
    element.closest(selector)
  );

  return match ? match[1] : "page";
}

function getServiceName(element) {
  if (element.dataset.bookService) return element.dataset.bookService;

  const serviceCard = element.closest(".svc-card[data-service]");
  if (serviceCard) {
    const heading = serviceCard.querySelector("h3");
    if (heading) return heading.textContent.trim();
    return serviceCard.dataset.service || "";
  }

  const teamMember = element.closest(".team-member");
  if (teamMember) {
    const heading = teamMember.querySelector("h2");
    if (heading) return `Book with ${heading.textContent.trim()}`;
  }

  return "";
}

function getLinkDestination(element) {
  return (
    element.getAttribute("href") ||
    element.dataset.bookingUrl ||
    element.action ||
    ""
  );
}

function trackBeautyLodgeEvent(eventName, parameters = {}) {
  const eventData = {
    event: eventName,
    page_name: getPageName(),
    page_path: window.location.pathname,
    ...parameters
  };

  window.dataLayer = window.dataLayer || [];
  window.dataLayer.push(eventData);
}

function trackBookingClick(element, extraParameters = {}) {
  const serviceName = getServiceName(element);
  const buttonLocation = getButtonLocation(element);
  const destination = getLinkDestination(element) || SETMORE_URL;

  const parameters = {
    button_location: buttonLocation,
    destination,
    link_text: element.textContent.trim(),
    ...extraParameters
  };

  if (serviceName) {
    parameters.service_name = serviceName;
  }

  trackBeautyLodgeEvent("book_now_click", parameters);

  if (serviceName) {
    trackBeautyLodgeEvent("service_book_click", parameters);
  }
}

function initAnalyticsTracking() {
  document.addEventListener("click", (event) => {
    const bookButton = event.target.closest("[data-book]");
    if (bookButton) {
      trackBookingClick(bookButton);
      return;
    }

    const instagramLink = event.target.closest("[data-ig]");
    if (instagramLink) {
      trackBeautyLodgeEvent("instagram_click", {
        button_location: getButtonLocation(instagramLink),
        destination: getLinkDestination(instagramLink) || INSTAGRAM_URL,
        link_text: instagramLink.textContent.trim() || "Instagram"
      });
      return;
    }

    const phoneLink = event.target.closest('a[href^="tel:"]');
    if (phoneLink) {
      trackBeautyLodgeEvent("phone_click", {
        button_location: getButtonLocation(phoneLink),
        destination: getLinkDestination(phoneLink),
        link_text: phoneLink.textContent.trim()
      });
      return;
    }

    const emailLink = event.target.closest('a[href^="mailto:"]');
    if (emailLink) {
      trackBeautyLodgeEvent("email_click", {
        button_location: getButtonLocation(emailLink),
        destination: getLinkDestination(emailLink),
        link_text: emailLink.textContent.trim()
      });
      return;
    }

    const directionsLink = event.target.closest(
      'a[href*="google.com/maps/dir"]'
    );
    if (directionsLink) {
      trackBeautyLodgeEvent("directions_click", {
        button_location: getButtonLocation(directionsLink),
        destination: getLinkDestination(directionsLink),
        link_text: directionsLink.textContent.trim()
      });
      return;
    }

    const serviceCard = event.target.closest(".svc-card[data-service]");
    if (serviceCard) {
      const heading = serviceCard.querySelector("h3");

      trackBeautyLodgeEvent("service_click", {
        button_location: getButtonLocation(serviceCard),
        service_id: serviceCard.dataset.service,
        service_name: heading
          ? heading.textContent.trim()
          : serviceCard.dataset.service
      });
    }
  });

  document.addEventListener("submit", (event) => {
    const form = event.target.closest(".contact-form");
    if (!form) return;

    const service = form.querySelector('[name="service"]')?.value || "";

    window.sessionStorage.setItem(
      "beautyLodgeContactSubmitPending",
      "true"
    );

    trackBeautyLodgeEvent("contact_form_submit", {
      button_location: getButtonLocation(form),
      destination: form.action,
      service_name: service || undefined
    });
  });
}

function escapeEventText(value = "") {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function parseEventDate(value) {
  if (!value) return null;
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? null : date;
}

function formatEventMonth(date) {
  return new Intl.DateTimeFormat("en-US", {
    month: "short"
  }).format(date).toUpperCase();
}

function formatEventDay(date) {
  return new Intl.DateTimeFormat("en-US", {
    day: "numeric"
  }).format(date);
}

function formatEventSchedule(event) {
  const start = parseEventDate(event.start);
  const end = parseEventDate(event.end);

  if (!start) return "Date to be announced";

  const dateText = new Intl.DateTimeFormat("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
    year: "numeric"
  }).format(start);

  if (event.allDay) return dateText;

  const startTime = new Intl.DateTimeFormat("en-US", {
    hour: "numeric",
    minute: "2-digit"
  }).format(start);

  if (!end) return `${dateText} · ${startTime}`;

  const endTime = new Intl.DateTimeFormat("en-US", {
    hour: "numeric",
    minute: "2-digit"
  }).format(end);

  return `${dateText} · ${startTime}-${endTime}`;
}

function getShortDescription(description = "") {
  const cleaned = String(description)
    .replace(/<[^>]*>/g, "")
    .replace(/\s+/g, " ")
    .trim();

  if (!cleaned) return "";
  return cleaned.length <= 180
    ? cleaned
    : `${cleaned.slice(0, 180).trim()}...`;
}

function createPopupEventCard(event) {
  const start = parseEventDate(event.start);
  if (!start) return "";

  const title = escapeEventText(
    event.title || "Beauty Lodge Pop-Up"
  );
  const location = escapeEventText(event.location || "");
  const description = escapeEventText(
    getShortDescription(event.description || "")
  );
  const schedule = escapeEventText(
    formatEventSchedule(event)
  );

  const locationHtml = location
    ? `
      <p class="popup-location">
        <svg
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="1.6"
          aria-hidden="true"
        >
          <path d="M12 21s6-5.2 6-11a6 6 0 1 0-12 0c0 5.8 6 11 6 11Z" />
          <circle cx="12" cy="10" r="2.2" />
        </svg>
        <span>${location}</span>
      </p>
    `
    : "";

  const descriptionHtml = description
    ? `<p class="popup-description">${description}</p>`
    : "";

  return `
    <article class="popup-card">
      <div class="popup-date">
        <span class="popup-month">${formatEventMonth(start)}</span>
        <span class="popup-day">${formatEventDay(start)}</span>
      </div>

      <div class="popup-content">
        <h4>${title}</h4>
        <p class="popup-schedule">${schedule}</p>
        ${locationHtml}
        ${descriptionHtml}
      </div>
    </article>
  `;
}

function configureDynamicInstagramLink(container) {
  const button = container.querySelector("[data-ig]");

  if (button) {
    button.href = INSTAGRAM_URL;
    button.target = "_blank";
    button.rel = "noopener";
  }
}

function renderEmptyCalendar(container) {
  container.innerHTML = `
    <div class="popup-empty">
      <p class="eyebrow">More Dates Coming Soon</p>
      <h4>No upcoming pop-ups are scheduled yet.</h4>
      <p>
        Follow Beauty Lodge on Instagram for announcements and
        newly added market dates.
      </p>
      <a class="btn btn-light btn-sm" data-ig href="#">
        Follow on Instagram
      </a>
    </div>
  `;

  configureDynamicInstagramLink(container);
}

function renderCalendarError(container) {
  container.innerHTML = `
    <div class="popup-empty">
      <p class="eyebrow">Upcoming Events</p>
      <h4>The event calendar is temporarily unavailable.</h4>
      <p>
        Please check back soon or visit Instagram for the latest
        pop-up and market announcements.
      </p>
      <a class="btn btn-light btn-sm" data-ig href="#">
        Follow on Instagram
      </a>
    </div>
  `;

  configureDynamicInstagramLink(container);
}

async function loadPopupEvents() {
  const container = document.getElementById("popup-events");
  if (!container) return;

  try {
    const cacheBuster = Date.now();
    const response = await fetch(
      `${EVENTS_JSON_URL}?v=${cacheBuster}`,
      { cache: "no-store" }
    );

    if (!response.ok) {
      throw new Error(`Events request returned ${response.status}`);
    }

    const data = await response.json();
    const now = new Date();

    const events = Array.isArray(data.events)
      ? data.events
          .filter((event) => {
            const end =
              parseEventDate(event.end) ||
              parseEventDate(event.start);
            return end && end >= now;
          })
          .sort(
            (a, b) =>
              parseEventDate(a.start) -
              parseEventDate(b.start)
          )
          .slice(0, MAX_POPUP_EVENTS)
      : [];

    if (events.length === 0) {
      renderEmptyCalendar(container);
      return;
    }

    container.innerHTML = events
      .map(createPopupEventCard)
      .join("");
  } catch (error) {
    console.error("Unable to load upcoming events:", error);
    renderCalendarError(container);
  }
}



/* ============================================================
   SERVICE AVAILABILITY
   Controlled by assets/services.json through GitHub Actions.
   States: available, unavailable, hidden.
   ============================================================ */

const SERVICES_CONFIG_URL = "assets/services.json";

function addUnavailableBadge(card) {
  if (card.querySelector(".service-status")) return;

  const badge = document.createElement("p");
  badge.className = "service-status";
  badge.textContent = "Temporarily unavailable";

  const heading = card.querySelector("h3");
  if (heading) heading.insertAdjacentElement("afterend", badge);
}

function setServiceCardState(card, state) {
  const bookButton = card.querySelector("[data-book]");

  card.hidden = false;
  card.classList.remove("service-unavailable");

  const existingBadge = card.querySelector(".service-status");
  if (existingBadge) existingBadge.remove();

  if (bookButton) {
    bookButton.removeAttribute("aria-disabled");
    bookButton.removeAttribute("tabindex");
    bookButton.classList.remove("btn-disabled");
    bookButton.textContent = "Book";
  }

  if (state === "hidden") {
    card.hidden = true;
    return;
  }

  if (state === "unavailable") {
    card.classList.add("service-unavailable");
    addUnavailableBadge(card);

    if (bookButton) {
      bookButton.classList.add("btn-disabled");
      bookButton.setAttribute("aria-disabled", "true");
      bookButton.setAttribute("tabindex", "-1");
      bookButton.removeAttribute("data-book");
      bookButton.setAttribute("href", "#");
      bookButton.textContent = "Unavailable";
    }
  }
}

function hideEmptyServiceGroups() {
  document.querySelectorAll(".svc-group").forEach((group) => {
    const cards = [...group.querySelectorAll(".svc-card[data-service]")];
    group.hidden = cards.length > 0 && cards.every((card) => card.hidden);
  });
}

async function loadServiceAvailability() {
  const cards = document.querySelectorAll(".svc-card[data-service]");
  if (!cards.length) return;

  try {
    const response = await fetch(`${SERVICES_CONFIG_URL}?v=${Date.now()}`, {
      cache: "no-store"
    });

    if (!response.ok) {
      throw new Error(`Services configuration returned HTTP ${response.status}`);
    }

    const config = await response.json();

    cards.forEach((card) => {
      const serviceId = card.dataset.service;
      const state = config?.[serviceId]?.state || "available";
      setServiceCardState(card, state);
    });

    hideEmptyServiceGroups();
  } catch (error) {
    console.error("Unable to load service availability:", error);
    cards.forEach((card) => setServiceCardState(card, "available"));
  }
}




/* ============================================================
   LASH STYLE FINDER
   ============================================================ */

const LASH_STYLE_OPTIONS = {
  lift: {
    tabId: "lash-choice-lift",
    title: "Lash Lift & Tint",
    image: "assets/service-lash-lift-tint.jpeg",
    imageAlt: "Lash Lift and Tint result",
    description:
      "A low-maintenance enhancement that lifts, curls, and deepens your natural lashes without adding extensions.",
    look: "Lifted and effortless",
    maintenance: "Typically lasts 6–8 weeks",
    duration: "1 hr 15 min",
    price: "$100"
  },
  natural: {
    tabId: "lash-choice-natural",
    title: "Natural Full Set",
    image: "assets/card-fullset.jpg",
    imageAlt: "Natural Full Set lash result",
    description:
      "A soft, polished extension look that adds length and definition without appearing overly dramatic.",
    look: "Natural and defined",
    maintenance: "Refill every 2–3 weeks",
    duration: "1 hr 45 min",
    price: "$140"
  },
  volume: {
    tabId: "lash-choice-volume",
    title: "Volume Set",
    image: "assets/card-volume.jpg",
    imageAlt: "Volume Set lash result",
    description:
      "A fuller, more noticeable extension look created with lightweight volume fans and customized density.",
    look: "Full and dramatic",
    maintenance: "Refill every 2–3 weeks",
    duration: "2 hr",
    price: "$155"
  }
};

function trackLashFinderEvent(eventName, styleKey) {
  const option = LASH_STYLE_OPTIONS[styleKey];
  if (!option) return;

  trackBeautyLodgeEvent(eventName, {
    button_location: "lash_finder",
    lash_style: styleKey,
    service_name: option.title,
    recommended_service: option.title
  });
}

function initLashStyleFinder() {
  const finder = document.querySelector(".lash-finder");
  if (!finder) return;

  const tabs = [...finder.querySelectorAll("[data-lash-style]")];
  const result = finder.querySelector("#lash-finder-result");
  const resultImage = finder.querySelector("[data-lash-result-image]");
  const resultTitle = finder.querySelector("[data-lash-result-title]");
  const resultDescription = finder.querySelector(
    "[data-lash-result-description]"
  );
  const resultLook = finder.querySelector("[data-lash-result-look]");
  const resultMaintenance = finder.querySelector(
    "[data-lash-result-maintenance]"
  );
  const resultDuration = finder.querySelector(
    "[data-lash-result-duration]"
  );
  const resultPrice = finder.querySelector("[data-lash-result-price]");
  const resultBook = finder.querySelector("[data-lash-result-book]");

  if (
    !tabs.length ||
    !result ||
    !resultImage ||
    !resultTitle ||
    !resultDescription ||
    !resultLook ||
    !resultMaintenance ||
    !resultDuration ||
    !resultPrice ||
    !resultBook
  ) {
    return;
  }

  let activeStyle = "natural";

  function renderStyle(styleKey, shouldTrack = true) {
    const option = LASH_STYLE_OPTIONS[styleKey];
    if (!option || styleKey === activeStyle && shouldTrack) {
      return;
    }

    activeStyle = styleKey;
    result.classList.add("is-updating");

    window.setTimeout(() => {
      tabs.forEach((tab) => {
        const selected = tab.dataset.lashStyle === styleKey;
        tab.classList.toggle("is-active", selected);
        tab.setAttribute("aria-selected", selected ? "true" : "false");
        tab.setAttribute("tabindex", selected ? "0" : "-1");
      });

      result.setAttribute("aria-labelledby", option.tabId);
      resultImage.src = option.image;
      resultImage.alt = option.imageAlt;
      resultTitle.textContent = option.title;
      resultDescription.textContent = option.description;
      resultLook.textContent = option.look;
      resultMaintenance.textContent = option.maintenance;
      resultDuration.textContent = option.duration;
      resultPrice.textContent = option.price;
      resultBook.dataset.bookService = option.title;
      resultBook.setAttribute(
        "aria-label",
        `Book ${option.title} with Beauty Lodge by Anna`
      );

      result.classList.remove("is-updating");

      if (shouldTrack) {
        trackLashFinderEvent("lash_style_select", styleKey);
      }
    }, 120);
  }

  tabs.forEach((tab, index) => {
    tab.addEventListener("click", () => {
      renderStyle(tab.dataset.lashStyle);
    });

    tab.addEventListener("keydown", (event) => {
      if (!["ArrowLeft", "ArrowRight", "ArrowUp", "ArrowDown"].includes(
        event.key
      )) {
        return;
      }

      event.preventDefault();

      const direction =
        event.key === "ArrowRight" || event.key === "ArrowDown"
          ? 1
          : -1;

      const nextIndex = (index + direction + tabs.length) % tabs.length;
      const nextTab = tabs[nextIndex];

      nextTab.focus();
      renderStyle(nextTab.dataset.lashStyle);
    });
  });

  resultBook.addEventListener("click", () => {
    trackLashFinderEvent("lash_comparison_book_click", activeStyle);
  });
}




/* ============================================================
   PERMANENT JEWELRY MINI-SITE
   ============================================================ */

function initJewelryNavigation() {
  const currentPage = window.location.pathname.split("/").pop() || "jewelry.html";
  document.querySelectorAll(".jewelry-subnav a").forEach((link) => {
    const hrefPage = (link.getAttribute("href") || "").split("#")[0];
    if (hrefPage === currentPage) link.setAttribute("aria-current", "page");
  });

  const dropdown = document.querySelector(".nav-dropdown");
  const button = dropdown?.querySelector(".nav-dropdown-toggle");
  if (!dropdown || !button) return;

  button.addEventListener("click", (event) => {
    event.stopPropagation();
    const open = dropdown.classList.toggle("open");
    button.setAttribute("aria-expanded", open ? "true" : "false");
  });

  document.addEventListener("click", (event) => {
    if (!dropdown.contains(event.target)) {
      dropdown.classList.remove("open");
      button.setAttribute("aria-expanded", "false");
    }
  });

  document.addEventListener("keydown", (event) => {
    if (event.key === "Escape") {
      dropdown.classList.remove("open");
      button.setAttribute("aria-expanded", "false");
    }
  });
}

function initJewelryStyleFinder() {
  const finder = document.querySelector("[data-jewelry-finder]");
  if (!finder) return;

  const state = {
    placement: "Bracelet",
    style: "Delicate",
    accent: "Chain only"
  };

  const summaryTitle = finder.querySelector("[data-jewelry-summary-title]");
  const summaryImage = finder.querySelector("[data-jewelry-summary-image]");
  const bookButton = finder.querySelector("[data-jewelry-book]");

  const placementPreview = {
    Bracelet: { src: "assets/gallery-1.jpg", alt: "Bracelet permanent jewelry inspiration" },
    Anklet: { src: "assets/gallery-6.jpg", alt: "Anklet permanent jewelry inspiration" },
    Necklace: { src: "assets/gallery-5.jpg", alt: "Necklace permanent jewelry inspiration" }
  };

  function updateSummary(track = true) {
    finder.querySelectorAll("[data-jewelry-summary]").forEach((element) => {
      const key = element.dataset.jewelrySummary;
      if (key && state[key]) element.textContent = state[key];
    });

    if (summaryTitle) {
      summaryTitle.textContent = `${state.style} ${state.placement}`;
    }

    if (summaryImage) {
      const preview = placementPreview[state.placement] || placementPreview.Bracelet;
      summaryImage.classList.add("is-changing");
      window.setTimeout(() => {
        summaryImage.src = preview.src;
        summaryImage.alt = preview.alt;
        summaryImage.classList.remove("is-changing");
      }, 90);
    }

    if (bookButton) {
      bookButton.dataset.bookService =
        `Permanent Jewelry Fitting — ${state.style} ${state.placement}, ${state.accent}`;
      bookButton.setAttribute(
        "aria-label",
        `Book a ${state.style.toLowerCase()} ${state.placement.toLowerCase()} permanent jewelry fitting`
      );
    }

    if (track) {
      trackBeautyLodgeEvent("jewelry_style_update", {
        button_location: "jewelry_style_finder",
        jewelry_placement: state.placement,
        jewelry_style: state.style,
        jewelry_accent: state.accent
      });
    }
  }

  finder.querySelectorAll("[data-jewelry-group]").forEach((group) => {
    const key = group.dataset.jewelryGroup;

    group.querySelectorAll(".jewelry-choice").forEach((button) => {
      button.addEventListener("click", () => {
        group.querySelectorAll(".jewelry-choice").forEach((choice) => {
          const selected = choice === button;
          choice.classList.toggle("is-active", selected);
          choice.setAttribute("aria-pressed", selected ? "true" : "false");
        });

        state[key] = button.dataset.value || button.textContent.trim();
        updateSummary(true);
      });
    });
  });

  updateSummary(false);
}


document.addEventListener("DOMContentLoaded", async () => {
  await loadServiceAvailability();

  document.querySelectorAll("[data-book]").forEach((el) => {
    el.classList.add("anywhere-book-now-button");
    el.setAttribute("data-booking-url", SETMORE_URL);
    el.setAttribute("data-new-tab", "false");
    el.setAttribute("href", SETMORE_URL);
    el.setAttribute("rel", "noopener");
  });

  initLashStyleFinder();

  if (!document.getElementById("anywhere_book_now_script")) {
    const script = document.createElement("script");
    script.id = "anywhere_book_now_script";
    script.src =
      "https://assets.setmore.com/integration/book-now/live/v1/anywhere-book-now.js";
    document.body.appendChild(script);
  }

  document.querySelectorAll("[data-ig]").forEach((el) => {
    el.setAttribute("href", INSTAGRAM_URL);
    el.setAttribute("target", "_blank");
    el.setAttribute("rel", "noopener");
  });

  initAnalyticsTracking();

  if (
    getPageName() === "contact-success" &&
    window.sessionStorage.getItem("beautyLodgeContactSubmitPending")
  ) {
    window.sessionStorage.removeItem("beautyLodgeContactSubmitPending");

    trackBeautyLodgeEvent("contact_form_submit", {
      button_location: "contact_success",
      form_status: "success"
    });
  }

  const toggle = document.querySelector(".nav-toggle");
  const links = document.querySelector(".nav-links");

  if (toggle && links) {
    toggle.addEventListener("click", () => {
      const open = links.classList.toggle("open");
      toggle.setAttribute(
        "aria-expanded",
        open ? "true" : "false"
      );
    });

    links.querySelectorAll("a").forEach((anchor) => {
      anchor.addEventListener("click", () => {
        links.classList.remove("open");
        toggle.setAttribute("aria-expanded", "false");
      });
    });
  }

  initJewelryNavigation();
  initJewelryStyleFinder();

  const reduceMotion = window.matchMedia(
    "(prefers-reduced-motion: reduce)"
  ).matches;
  const revealItems = document.querySelectorAll(".reveal");

  if (
    reduceMotion ||
    !("IntersectionObserver" in window)
  ) {
    revealItems.forEach((el) => el.classList.add("in"));
  } else {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add("in");
            observer.unobserve(entry.target);
          }
        });
      },
      {
        threshold: 0.12,
        rootMargin: "0px 0px -60px 0px"
      }
    );

    revealItems.forEach((el) => observer.observe(el));
  }

  loadPopupEvents();

  window.setInterval(
    loadPopupEvents,
    CALENDAR_REFRESH_MINUTES * 60 * 1000
  );
});